set -e
true
true
/home/omri/miniconda3/bin/spades-core /home/omri/Identiphase/homeomriIdentiphase/K21/configs/config.info /home/omri/Identiphase/homeomriIdentiphase/K21/configs/isolate_mode.info
/home/omri/miniconda3/bin/spades-core /home/omri/Identiphase/homeomriIdentiphase/K33/configs/config.info /home/omri/Identiphase/homeomriIdentiphase/K33/configs/isolate_mode.info
/home/omri/miniconda3/bin/spades-core /home/omri/Identiphase/homeomriIdentiphase/K55/configs/config.info /home/omri/Identiphase/homeomriIdentiphase/K55/configs/isolate_mode.info
/home/omri/miniconda3/bin/python3 /home/omri/miniconda3/share/spades/spades_pipeline/scripts/copy_files.py /home/omri/Identiphase/homeomriIdentiphase/K55/before_rr.fasta /home/omri/Identiphase/homeomriIdentiphase/before_rr.fasta /home/omri/Identiphase/homeomriIdentiphase/K55/assembly_graph_after_simplification.gfa /home/omri/Identiphase/homeomriIdentiphase/assembly_graph_after_simplification.gfa /home/omri/Identiphase/homeomriIdentiphase/K55/final_contigs.fasta /home/omri/Identiphase/homeomriIdentiphase/contigs.fasta /home/omri/Identiphase/homeomriIdentiphase/K55/first_pe_contigs.fasta /home/omri/Identiphase/homeomriIdentiphase/first_pe_contigs.fasta /home/omri/Identiphase/homeomriIdentiphase/K55/strain_graph.gfa /home/omri/Identiphase/homeomriIdentiphase/strain_graph.gfa /home/omri/Identiphase/homeomriIdentiphase/K55/scaffolds.fasta /home/omri/Identiphase/homeomriIdentiphase/scaffolds.fasta /home/omri/Identiphase/homeomriIdentiphase/K55/scaffolds.paths /home/omri/Identiphase/homeomriIdentiphase/scaffolds.paths /home/omri/Identiphase/homeomriIdentiphase/K55/assembly_graph_with_scaffolds.gfa /home/omri/Identiphase/homeomriIdentiphase/assembly_graph_with_scaffolds.gfa /home/omri/Identiphase/homeomriIdentiphase/K55/assembly_graph.fastg /home/omri/Identiphase/homeomriIdentiphase/assembly_graph.fastg /home/omri/Identiphase/homeomriIdentiphase/K55/final_contigs.paths /home/omri/Identiphase/homeomriIdentiphase/contigs.paths
true
/home/omri/miniconda3/bin/python3 /home/omri/miniconda3/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/omri/Identiphase/homeomriIdentiphase/scaffolds.fasta --misc_dir /home/omri/Identiphase/homeomriIdentiphase/misc --threshold_for_breaking_scaffolds 3
true
